//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllSaleEmployeeView
    {
        public string WHID { get; set; }
        public string WHName { get; set; }
        public string CashVan { get; set; }
        public string SaleEmpID { get; set; }
        public string FullName { get; set; }
    }
}
