//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArCustomerView
    {
        public string CustomerID { get; set; }
        public Nullable<int> CustomerTypeID { get; set; }
        public string CustomerCode { get; set; }
        public string CustTitle { get; set; }
        public string CustName { get; set; }
        public int ShopTypeID { get; set; }
        public string ShopTypeName { get; set; }
        public string SalAreaID { get; set; }
        public string SalAreaName { get; set; }
        public string WHID { get; set; }
        public string WHName { get; set; }
        public string CustomerRefCode { get; set; }
        public byte[] CustomerImg { get; set; }
        public string CustShortName { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public System.DateTime CrDate { get; set; }
        public string BillTo { get; set; }
        public string ShipTo { get; set; }
        public string Contact { get; set; }
        public string Telephone { get; set; }
        public string EmpID { get; set; }
        public string FirstName { get; set; }
        public string CustomerSAPCode { get; set; }
        public byte CreditDay { get; set; }
        public short Seq { get; set; }
        public bool FlagMember { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public string ProvinceName { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string DistrictCode { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string AreaName { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Email { get; set; }
        public string TaxId { get; set; }
        public string Fax { get; set; }
        public bool FlagDel { get; set; }
        public Nullable<int> PriceGroupID { get; set; }
        public string PriceGroupName { get; set; }
        public string AddressNo { get; set; }
        public string lane { get; set; }
        public string Street { get; set; }
        public bool FlagBill { get; set; }
        public string PostalCode { get; set; }
    }
}
