//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetCust_Routing
    {
        public long Number { get; set; }
        public string WHID { get; set; }
        public Nullable<short> SeqArea { get; set; }
        public string SalAreaID { get; set; }
        public string SalAreaName { get; set; }
        public string CustomerID { get; set; }
        public short Seq { get; set; }
        public string CustName { get; set; }
        public string Telephone { get; set; }
        public string BillTo { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
    }
}
