//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetCoreCardReason
    {
        public int AutoID { get; set; }
        public string CustomerID { get; set; }
        public string WHID { get; set; }
        public string VisitDate { get; set; }
        public string CauseName { get; set; }
        public Nullable<int> VisitTime { get; set; }
        public Nullable<decimal> SalesOrder { get; set; }
    }
}
