//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetProduct
    {
        public long Number { get; set; }
        public string ProductID { get; set; }
        public short Seq { get; set; }
        public string ProductName { get; set; }
        public string ProductShortName { get; set; }
        public string Flavour { get; set; }
        public string VatType { get; set; }
        public int ProductSubGroupID { get; set; }
        public string ProductSubGroupName { get; set; }
        public int ProductGroupID { get; set; }
        public string ProductGroupName { get; set; }
        public Nullable<int> UomSetID { get; set; }
        public string UomSetName { get; set; }
        public Nullable<int> BaseQty { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<decimal> SellPriceVat { get; set; }
        public Nullable<int> PriceGroupID { get; set; }
        public Nullable<int> SaleTypeID { get; set; }
    }
}
