//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetTotalBill
    {
        public string DocNo { get; set; }
        public string DocTypeCode { get; set; }
        public string DocStatus { get; set; }
        public string DocDate { get; set; }
        public string CustomerID { get; set; }
        public string WHID { get; set; }
        public decimal TotalDue { get; set; }
    }
}
