//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductView
    {
        public string ProductID { get; set; }
        public string ProductRefCode { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public string ProductTypeName { get; set; }
        public int ProductGroupID { get; set; }
        public string ProductGroupName { get; set; }
        public int ProductSubGroupID { get; set; }
        public string ProductSubGroupName { get; set; }
        public string Barcode { get; set; }
        public string ProductName { get; set; }
        public string ProductShortName { get; set; }
        public int SaleUomID { get; set; }
        public string ProductUomName { get; set; }
        public string Flavour { get; set; }
        public bool VatType { get; set; }
        public short ReorderPoint { get; set; }
        public short MinPoint { get; set; }
        public decimal Weight { get; set; }
        public decimal Size { get; set; }
        public bool IsFulfill { get; set; }
        public short Seq { get; set; }
        public byte[] ProductImg { get; set; }
        public string SizeUOM { get; set; }
        public string WeightUOM { get; set; }
        public int PurchaseUomID { get; set; }
        public Nullable<decimal> StandardCost { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
        public bool FlagNew { get; set; }
        public bool FlagEdit { get; set; }
        public int ProductBrandID { get; set; }
        public int ProductLine { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SaleTypeID { get; set; }
    }
}
