//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_DSR_KPI
    {
        public string WHID { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string BranchID { get; set; }
        public string BranchName { get; set; }
        public string EmpName { get; set; }
        public string Van { get; set; }
        public Nullable<decimal> ActualExVat { get; set; }
        public Nullable<decimal> ActualIncVat { get; set; }
        public Nullable<int> CustBought { get; set; }
        public Nullable<int> SKU { get; set; }
        public Nullable<int> Visited { get; set; }
        public Nullable<int> Invoice { get; set; }
    }
}
