//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HQ_Promotion
    {
        public string PromotionID { get; set; }
        public string PromotionType { get; set; }
        public string PromotionPattern { get; set; }
        public string StepCondition1 { get; set; }
        public string SKUGroupID1 { get; set; }
        public Nullable<int> ConditionStart { get; set; }
        public Nullable<int> ConditionEnd { get; set; }
        public string DisCountPattern { get; set; }
        public Nullable<decimal> DisCountAmt { get; set; }
        public string PruductGroupRewardID { get; set; }
        public Nullable<int> PruductGroupRewardAmt { get; set; }
        public string PruductGroupRewardID2 { get; set; }
        public Nullable<int> PruductGroupRewardAmt2 { get; set; }
        public string StepCondition2 { get; set; }
        public Nullable<int> SKUGroupID2 { get; set; }
        public string RewardID { get; set; }
        public Nullable<int> PromotionPriority { get; set; }
        public Nullable<int> HitLimit { get; set; }
        public Nullable<bool> Recomputable { get; set; }
        public Nullable<bool> IgnoreApplied { get; set; }
        public Nullable<bool> IsUseCoupon { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> PlusSaleFrom { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> SaleTypeID { get; set; }
    }
}
