//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TL_PODetail
    {
        public long AutoID { get; set; }
        public string DocNo { get; set; }
        public string DocTypeCode { get; set; }
        public string DocStatus { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string CustomerID { get; set; }
        public Nullable<short> Line { get; set; }
        public string ProductID { get; set; }
        public string OrderUom { get; set; }
        public Nullable<int> OrderUnit { get; set; }
        public Nullable<decimal> OrderQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<byte> VatType { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public string LineDiscountType { get; set; }
        public Nullable<decimal> LineDiscountRate { get; set; }
        public Nullable<decimal> LineDiscount { get; set; }
        public string LineRemark { get; set; }
        public Nullable<int> FreeQty { get; set; }
        public Nullable<byte> FreeUom { get; set; }
        public Nullable<int> FreeUnit { get; set; }
        public string WHID { get; set; }
    }
}
