//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ApSupplier
    {
        public string SupplierID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierRefCode { get; set; }
        public string SuppTitle { get; set; }
        public string SuppName { get; set; }
        public string SuppShortName { get; set; }
        public Nullable<int> SupplierTypeID { get; set; }
        public string BillTo { get; set; }
        public string ShipTo { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Contact { get; set; }
        public string AddressNo { get; set; }
        public string lane { get; set; }
        public string Street { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string PostalCode { get; set; }
        public string Email { get; set; }
        public byte CreditDay { get; set; }
        public string TaxId { get; set; }
        public Nullable<bool> VatType { get; set; }
        public string DiscountType { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string SaleAp { get; set; }
        public string SaleApTel { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
    }
}
