//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BranchWarehouse
    {
        public string WHID { get; set; }
        public string BranchID { get; set; }
        public string WHCode { get; set; }
        public string WHName { get; set; }
        public string WHSeq { get; set; }
        public string License { get; set; }
        public int WHType { get; set; }
        public string SaleEmpID { get; set; }
        public string DriverEmpID { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
        public int VanType { get; set; }
        public string HelperEmpID { get; set; }
        public string POSNo { get; set; }
    }
}
