//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CfgKeyField
    {
        public int AutoID { get; set; }
        public string TableName { get; set; }
        public string DataName { get; set; }
        public string FieldName { get; set; }
        public string RefFieldName { get; set; }
        public Nullable<bool> IsPKey { get; set; }
        public bool FlagSend { get; set; }
    }
}
