//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LytRedeem
    {
        public string DocNo { get; set; }
        public short Line { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string BranchID { get; set; }
        public string WHID { get; set; }
        public string CustomerID { get; set; }
        public string ProductID { get; set; }
        public int BaseQty { get; set; }
        public Nullable<int> PayPoint { get; set; }
        public int DocStatus { get; set; }
        public string RefDO { get; set; }
        public Nullable<System.DateTime> DODate { get; set; }
        public string RefCM { get; set; }
        public Nullable<System.DateTime> CMDate { get; set; }
        public string RefCMVan { get; set; }
        public string CMWHID { get; set; }
        public Nullable<int> ReceiveQty { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
    }
}
