//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AmtArCustomer
    {
        public short CycleNo { get; set; }
        public string Year { get; set; }
        public string DepotNo { get; set; }
        public string WHID { get; set; }
        public string SalAreaID { get; set; }
        public int AmtQty { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public System.DateTime EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
        public short Seq { get; set; }
        public string TitleName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SalAreaName { get; set; }
        public string ZoneName { get; set; }
        public string SaleEmpID { get; set; }
        public int ZoneID { get; set; }
        public string WHName { get; set; }
        public int WHSeq { get; set; }
        public string AmtArCustID { get; set; }
        public int VanTypeID { get; set; }
        public string VanTypeName { get; set; }
        public int VanTypeSeq { get; set; }
        public int WHType { get; set; }
    }
}
