//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TargetDetail
    {
        public int AutoID { get; set; }
        public int ProductSubGroupID { get; set; }
        public decimal ProductSubGroupPrice { get; set; }
        public int TargetQty { get; set; }
        public decimal TargetBaht { get; set; }
        public decimal TargetWeight { get; set; }
        public decimal TargetValue1 { get; set; }
        public decimal TargetValue2 { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
    }
}
