//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HQ_Promotion_Hit
    {
        public int PK { get; set; }
        public string DocNo { get; set; }
        public string PromotionID { get; set; }
        public Nullable<int> RoundHit { get; set; }
        public string SKUGroupID { get; set; }
        public Nullable<decimal> DisCountAmt { get; set; }
        public string SKUGroupRewardID { get; set; }
        public Nullable<int> SKUGroupRewardAmt { get; set; }
        public string RewardID { get; set; }
        public Nullable<bool> FlagDel { get; set; }
        public Nullable<bool> FlagSend { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public string SKUID { get; set; }
    }
}
