//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TL_VisitStock_HIS
    {
        public long AutoID { get; set; }
        public string BranchID { get; set; }
        public string WHID { get; set; }
        public string CustomerID { get; set; }
        public string DocNo { get; set; }
        public string VisitID { get; set; }
        public string VisitType { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string ProductID { get; set; }
        public Nullable<decimal> StockQty { get; set; }
    }
}
