//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesTrace
    {
        public int AutoID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string CustomerID { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<int> Status { get; set; }
        public string WHID { get; set; }
    }
}
