//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CoreCard
    {
        public int AutoID { get; set; }
        public string CustomerID { get; set; }
        public string WHID { get; set; }
        public string CauseName { get; set; }
        public string ProductSubGroupName { get; set; }
        public Nullable<decimal> C1 { get; set; }
        public Nullable<decimal> C2 { get; set; }
        public Nullable<decimal> C3 { get; set; }
        public Nullable<decimal> C4 { get; set; }
        public Nullable<decimal> C5 { get; set; }
    }
}
