//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AdmMenuList
    {
        public int GrpAutoID { get; set; }
        public int MIndex { get; set; }
        public string FormMode { get; set; }
        public string MenuName { get; set; }
        public string MenuText { get; set; }
        public string MenuText2 { get; set; }
        public string FormName { get; set; }
        public string MenuParent { get; set; }
        public int ImageIndex { get; set; }
        public int Status { get; set; }
        public bool FlagSend { get; set; }
    }
}
