//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PromotionReward
    {
        public int AutoProPrd { get; set; }
        public int ProductID { get; set; }
        public string RewardType { get; set; }
        public string GiftName { get; set; }
        public Nullable<int> GetQty { get; set; }
        public Nullable<decimal> ExchangePrice { get; set; }
        public bool FlagSend { get; set; }
    }
}
