//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TL_ArCustomer
    {
        public long AutoID { get; set; }
        public string CustomerID { get; set; }
        public string BranchID { get; set; }
        public string WHID { get; set; }
        public string EmpID { get; set; }
        public string SalAreaID { get; set; }
        public Nullable<int> ShopTypeID { get; set; }
        public Nullable<short> CustSeq { get; set; }
        public string CustTitle { get; set; }
        public string CustName { get; set; }
        public string CustShortName { get; set; }
        public string CustImage { get; set; }
        public string BillTo { get; set; }
        public string Tel { get; set; }
        public string Contact { get; set; }
        public string AddressNo { get; set; }
        public string Moo { get; set; }
        public string Lane { get; set; }
        public string Street { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public string PostalCode { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.DateTime> GPSDate { get; set; }
        public Nullable<int> CreditDay { get; set; }
        public Nullable<bool> FlagMember { get; set; }
        public Nullable<int> NetPoint { get; set; }
        public Nullable<bool> FlagBill { get; set; }
        public Nullable<bool> FlagNew { get; set; }
        public Nullable<bool> FlagEdit { get; set; }
        public Nullable<bool> FlagShelf { get; set; }
    }
}
