//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ArCustomerMapping
    {
        public int AutoID { get; set; }
        public string CustomerID { get; set; }
        public string CustName { get; set; }
        public string RefCustomerID { get; set; }
        public string RefCustName { get; set; }
        public string BillTo { get; set; }
        public string Telephone { get; set; }
        public string WHID { get; set; }
        public string SaleAreaID { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
    }
}
