//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VanType
    {
        public int AutoID { get; set; }
        public string Name { get; set; }
        public int Seq { get; set; }
        public short WHType { get; set; }
        public Nullable<int> SalAreaQty { get; set; }
        public string CrUser { get; set; }
        public System.DateTime CrDate { get; set; }
        public string EdUser { get; set; }
        public System.DateTime EdDate { get; set; }
        public bool FlagDel { get; set; }
    }
}
