//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BranchLog
    {
        public int AutoID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public string MachineName { get; set; }
        public int BranchID { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime LogTime { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string Username { get; set; }
        public string Event { get; set; }
        public string EventType { get; set; }
        public string IBDocNo { get; set; }
        public string INDocNo { get; set; }
        public int ShiftNo { get; set; }
        public System.DateTime CrDate { get; set; }
        public bool FlagSend { get; set; }
    }
}
