//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MstMenu
    {
        public int MenuID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string MenuName { get; set; }
        public string MenuText { get; set; }
        public string FormName { get; set; }
        public Nullable<int> MenuParent { get; set; }
        public byte[] MenuImage { get; set; }
        public Nullable<int> Seq { get; set; }
    }
}
