//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Banknote
    {
        public int BanknoteID { get; set; }
        public string BanknoteName { get; set; }
        public Nullable<int> BanknoteValue { get; set; }
        public string BanknoteType { get; set; }
        public bool FlagSend { get; set; }
    }
}
