//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DisplayImage
    {
        public int AutoID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Seq { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string EdUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public Nullable<bool> FlagDel { get; set; }
    }
}
