//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LytPointBonus
    {
        public int TransactionID { get; set; }
        public string TrnNo { get; set; }
        public Nullable<int> PointTypeID { get; set; }
        public string ProductID { get; set; }
        public int BaseQty { get; set; }
        public string RefDocNo { get; set; }
        public int DocStatus { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
        public Nullable<int> PayPoint { get; set; }
    }
}
