//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SendData
    {
        public System.DateTime DateSend { get; set; }
        public string WHID { get; set; }
        public string BranchID { get; set; }
        public Nullable<short> GenNo { get; set; }
        public Nullable<bool> FlagSend { get; set; }
        public Nullable<bool> FlagReceive { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string UserSend { get; set; }
    }
}
