//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SimOrder
    {
        public string BranchID { get; set; }
        public string DocNo { get; set; }
        public string WHID { get; set; }
        public string CustomerID { get; set; }
        public int ShopTypeID { get; set; }
        public System.DateTime DocDate { get; set; }
        public byte RevisionNo { get; set; }
        public string CustName { get; set; }
        public double Amount { get; set; }
        public Nullable<double> ExcVat { get; set; }
        public Nullable<double> IncVat { get; set; }
        public Nullable<double> VatAmt { get; set; }
        public double TotalDue { get; set; }
        public int Status { get; set; }
        public string EmpID { get; set; }
        public Nullable<byte> PayType { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public bool FlagSend { get; set; }
        public string RefLoadNo { get; set; }
        public string InvNo { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
    }
}
