//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LytPointTypePerBill
    {
        public int AutoNo { get; set; }
        public int KeyID { get; set; }
        public string BranchID { get; set; }
        public Nullable<int> CYear { get; set; }
        public Nullable<int> CycleNo { get; set; }
        public int PointTypeID { get; set; }
        public int BuyValue { get; set; }
        public int ConditionID { get; set; }
        public int GetPoint { get; set; }
        public bool IsCondition { get; set; }
        public string TypeSum { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
    }
}
