//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InvTransaction
    {
        public int TransactionID { get; set; }
        public string ProductID { get; set; }
        public string RefDocNo { get; set; }
        public int RefLineID { get; set; }
        public System.DateTime TrnDate { get; set; }
        public string BranchFrom { get; set; }
        public string WHFrom { get; set; }
        public string BranchTo { get; set; }
        public string WHTo { get; set; }
        public string TrnType { get; set; }
        public string DocTypeCode { get; set; }
        public Nullable<int> TrnUomID { get; set; }
        public string TrnUom { get; set; }
        public Nullable<decimal> BringQty { get; set; }
        public decimal TrnQtyIn { get; set; }
        public decimal TrnQtyOut { get; set; }
        public decimal TrnQty { get; set; }
        public Nullable<decimal> RemainQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public decimal UnitCost { get; set; }
        public string LineDiscountType { get; set; }
        public Nullable<decimal> LineDiscount { get; set; }
        public Nullable<decimal> TrnVat { get; set; }
        public decimal TrnValue { get; set; }
        public decimal TrnTotal { get; set; }
        public decimal CostValue { get; set; }
        public Nullable<int> Supplier { get; set; }
        public string Customer { get; set; }
        public string RefSONo { get; set; }
        public string CustPONo { get; set; }
        public string CustInvoiceNo { get; set; }
        public Nullable<int> Salesperson { get; set; }
        public string SalAreaID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
    }
}
