//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LytMember
    {
        public int MemberID { get; set; }
        public string BranchID { get; set; }
        public string MemberCode { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int NetPoint { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string Remark { get; set; }
        public string IDCode { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
    }
}
