//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InvWarehouse
    {
        public string ProductID { get; set; }
        public string WHID { get; set; }
        public decimal QtyOnHand { get; set; }
        public decimal QtyOnOrder { get; set; }
        public decimal QtyOnBackOrder { get; set; }
        public decimal QtyInTransit { get; set; }
        public decimal QtyOutTransit { get; set; }
        public decimal QtyOnReject { get; set; }
        public decimal MinimumQty { get; set; }
        public decimal MaximumQty { get; set; }
        public decimal ReOrderQty { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
    }
}
