//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalAreaDistrict
    {
        public string SalAreaID { get; set; }
        public string WHID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string DistrictCode { get; set; }
        public string DistrictName { get; set; }
        public string AreaName { get; set; }
        public string ProvinceName { get; set; }
        public string PostalCode { get; set; }
        public int AutoID { get; set; }
        public bool FlagSend { get; set; }
    }
}
