//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LytReportMenu
    {
        public int ReportID { get; set; }
        public int GroupID { get; set; }
        public string ReportNameEng { get; set; }
        public string ReportNameTh { get; set; }
        public string FileName { get; set; }
        public bool Status { get; set; }
    }
}
