//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TL_VisitShopImage
    {
        public int AutoID { get; set; }
        public string CustomerID { get; set; }
        public string VanID { get; set; }
        public string BranchID { get; set; }
        public Nullable<System.DateTime> Datamodify { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<bool> FlagModify { get; set; }
    }
}
