//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SimCustomer
    {
        public int AutoNo { get; set; }
        public string BranchID { get; set; }
        public string CustomerID { get; set; }
        public string CustName { get; set; }
        public string BillTo { get; set; }
        public string ShipTo { get; set; }
        public string Telephone { get; set; }
        public string Contact { get; set; }
        public string TaxId { get; set; }
        public string WHID { get; set; }
        public string WHName { get; set; }
        public string WHSeq { get; set; }
        public string SalAreaID { get; set; }
        public int ShopTypeID { get; set; }
        public string License { get; set; }
        public string SalAreaName { get; set; }
        public short Seq { get; set; }
        public bool FlagSend { get; set; }
        public string oldCode { get; set; }
    }
}
