//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VMIDetail
    {
        public long InternalID { get; set; }
        public string ProductID { get; set; }
        public decimal SumSale { get; set; }
        public decimal AvgSale { get; set; }
        public decimal SaleFactor { get; set; }
        public decimal SafetyFactor { get; set; }
        public decimal Stock { get; set; }
        public decimal SaleForecast { get; set; }
        public decimal Suggest { get; set; }
        public decimal Withdraw { get; set; }
    }
}
