//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SaleExpenseMaster
    {
        public string BranchID { get; set; }
        public string DocNo { get; set; }
        public string DocTypeCode { get; set; }
        public System.DateTime DocDate { get; set; }
        public string DocStatus { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public Nullable<short> ShiftNo { get; set; }
        public string EmpID { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Remark { get; set; }
        public string Comment { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
    }
}
