//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PRMaster
    {
        public int AutoID { get; set; }
        public string DocNo { get; set; }
        public byte RevisionNo { get; set; }
        public string DocTypeCode { get; set; }
        public string DocStatus { get; set; }
        public System.DateTime DocDate { get; set; }
        public string DocRef { get; set; }
        public string FromBranchID { get; set; }
        public string FromWHID { get; set; }
        public string RequestBy { get; set; }
        public string ToBranchID { get; set; }
        public string ToWHID { get; set; }
        public string StatusInOut { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string ReceiveBy { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string ShipBy { get; set; }
        public string ShipWHID { get; set; }
        public string SalAreaID { get; set; }
        public string EmpID { get; set; }
        public string ContactName { get; set; }
        public string ContactTel { get; set; }
        public string Shipto { get; set; }
        public string Remark { get; set; }
        public string Comment { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
    }
}
