//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CfgConnection
    {
        public string BranchID { get; set; }
        public string BranchName { get; set; }
        public string ConnStr { get; set; }
        public string ServerIP { get; set; }
        public Nullable<int> Seq { get; set; }
        public bool FlagSend { get; set; }
    }
}
