//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AdmControlList
    {
        public int ControlID { get; set; }
        public string ControlName { get; set; }
        public Nullable<int> FormID { get; set; }
        public string ControlText { get; set; }
        public Nullable<short> Seq { get; set; }
    }
}
