//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Branch
    {
        public string BranchID { get; set; }
        public string BranchCode { get; set; }
        public string BranchRefCode { get; set; }
        public string BranchName { get; set; }
        public int BranchGroupID { get; set; }
        public string Address { get; set; }
        public int SalAreaID { get; set; }
        public int ProvinceID { get; set; }
        public int AreaID { get; set; }
        public int DistrictID { get; set; }
        public int ShopTypeID { get; set; }
        public int PriceGroupID { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public System.TimeSpan CloseTime { get; set; }
        public Nullable<int> HQID { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> CanMinus { get; set; }
        public string SystemType { get; set; }
        public int PartID { get; set; }
        public string PartSeq { get; set; }
        public string TaxId { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
        public string SAPPlantID { get; set; }
        public string AgentID { get; set; }
        public string IPAddress { get; set; }
        public string ConnStr { get; set; }
        public string BranchRJCode { get; set; }
        public string FactoryCode { get; set; }
        public string FactoryLocation { get; set; }
        public string VanCode { get; set; }
        public string VanFormat { get; set; }
        public string BranchReject { get; set; }
        public string PremiumCode { get; set; }
        public string PremiumFormat { get; set; }
        public int BU { get; set; }
        public int DC { get; set; }
        public string BranchTax { get; set; }
        public string BranchTitle { get; set; }
        public string Prefix1 { get; set; }
        public string Prefix2 { get; set; }
        public Nullable<int> RunInit { get; set; }
        public Nullable<short> RunLength { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
    }
}
