//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SaleBranchDaily
    {
        public string BranchID { get; set; }
        public string ProductID { get; set; }
        public System.DateTime CloseDate { get; set; }
        public decimal SellPrice { get; set; }
        public System.TimeSpan CloseTime { get; set; }
        public decimal OpenQty { get; set; }
        public decimal QtyReceive { get; set; }
        public decimal QtyInTransit { get; set; }
        public decimal QtyOutTransit { get; set; }
        public decimal QtyOnSale { get; set; }
        public decimal QtyOnReject { get; set; }
        public decimal QtyBalance { get; set; }
        public decimal SaleAmount { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
    }
}
