//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TL_POMaster
    {
        public long AutoID { get; set; }
        public string DocNo { get; set; }
        public string DocTypeCode { get; set; }
        public string DocStatus { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string BranchID { get; set; }
        public string WHID { get; set; }
        public string EmpID { get; set; }
        public string SalAreaID { get; set; }
        public string CustomerID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> ExcVat { get; set; }
        public Nullable<decimal> IncVat { get; set; }
        public Nullable<decimal> VatAmt { get; set; }
        public Nullable<decimal> TotalDue { get; set; }
        public Nullable<int> RevisionNo { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string DiscountType { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<int> PayType { get; set; }
        public string Remark { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
        public Nullable<bool> FlagModify { get; set; }
    }
}
