//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TLMaster
    {
        public int AutoID { get; set; }
        public string AgentID { get; set; }
        public string DocDate { get; set; }
        public string LadyID { get; set; }
        public string WHID { get; set; }
        public string DocType { get; set; }
        public byte Revision { get; set; }
        public string Users { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagRecieve { get; set; }
    }
}
