//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductSubGroup
    {
        public int ProductSubGroupID { get; set; }
        public int ProductGroupID { get; set; }
        public string ProductSubGroupCode { get; set; }
        public string ProductSubGroupName { get; set; }
        public bool IsFulfill { get; set; }
        public byte[] ProductSubGroupImg { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
    }
}
