//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VANStock
    {
        public int PK { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocStatus { get; set; }
        public string ProductID { get; set; }
        public Nullable<decimal> OrderQty { get; set; }
        public Nullable<int> OrderUOM { get; set; }
        public string WHID { get; set; }
    }
}
