//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RemainingStock
    {
        public string ProductID { get; set; }
        public string WHID { get; set; }
        public System.DateTime TrnDate { get; set; }
        public Nullable<decimal> Beginnin { get; set; }
        public Nullable<decimal> TrnIn { get; set; }
        public Nullable<decimal> TrnOut { get; set; }
        public Nullable<decimal> Ending { get; set; }
    }
}
