//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PayDetail
    {
        public string DocNo { get; set; }
        public int AutoID { get; set; }
        public string WHID { get; set; }
        public decimal Send { get; set; }
        public decimal Deposit { get; set; }
        public decimal TotalSale { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
        public decimal Transfer { get; set; }
        public decimal Cheque { get; set; }
    }
}
