//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CfgFloatingHolidays
    {
        public int month { get; set; }
        public string day_of_week { get; set; }
        public int nth { get; set; }
        public string name { get; set; }
        public bool FlagSend { get; set; }
    }
}
