//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TL_ArCustomerShelf_HIS
    {
        public long AutoID { get; set; }
        public string CustomerID { get; set; }
        public string ShelfID { get; set; }
        public string ProductID { get; set; }
        public Nullable<bool> FlagNew { get; set; }
        public Nullable<bool> FlagEdit { get; set; }
        public Nullable<bool> FlagDel { get; set; }
        public string PathImage { get; set; }
    }
}
