//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LytReward
    {
        public int RewardID { get; set; }
        public string RewardCode { get; set; }
        public string RewardName { get; set; }
        public Nullable<short> Seq { get; set; }
        public string ProductID { get; set; }
        public Nullable<int> UsePoint { get; set; }
        public Nullable<int> GetQty { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public byte[] ProductImg { get; set; }
        public int BuyValue { get; set; }
        public string Remark { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
    }
}
