//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DocRunning
    {
        public int DocNum { get; set; }
        public string DocTypeCode { get; set; }
        public string YearDoc { get; set; }
        public string MonthDoc { get; set; }
        public string DayDoc { get; set; }
        public Nullable<int> RunDoc { get; set; }
        public Nullable<System.DateTime> ModifiledDate { get; set; }
        public string WHCode { get; set; }
        public bool FlagSend { get; set; }
    }
}
