//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LytCustTypeReward
    {
        public int AutoID { get; set; }
        public Nullable<int> CYear { get; set; }
        public Nullable<int> CycleNo { get; set; }
        public string CustTypeID { get; set; }
        public Nullable<decimal> MinVal { get; set; }
        public Nullable<decimal> MaxVal { get; set; }
        public string GetProductID { get; set; }
        public Nullable<short> GetQty { get; set; }
        public System.DateTime CrDate { get; set; }
        public string CrUser { get; set; }
        public Nullable<System.DateTime> EdDate { get; set; }
        public string EdUser { get; set; }
        public bool FlagDel { get; set; }
        public bool FlagSend { get; set; }
    }
}
