//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Rep_Visit_Per_Day_PO
    {
        public string WHID { get; set; }
        public string SalAreaID { get; set; }
        public Nullable<int> SalAreaSeq { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime DocDate { get; set; }
        public Nullable<decimal> SaleBaht { get; set; }
        public Nullable<decimal> SaleQty { get; set; }
    }
}
