//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Acutal_Sales_By_VAN
    {
        public string WHID { get; set; }
        public string EmpNme { get; set; }
        public string ProductSubGroupCode { get; set; }
        public string ProductSubGroupName { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
    }
}
