//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CountVisit_UBON
    {
        public Nullable<int> VisitCount { get; set; }
        public string BranchID { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
    }
}
