//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CUSTOMERHD
    {
        public string CustomerSAPCode { get; set; }
        public string CustName { get; set; }
        public string GroupCode { get; set; }
        public string GroupNum { get; set; }
        public string Address { get; set; }
        public string SlpCode { get; set; }
        public string Phone1 { get; set; }
        public string Fax { get; set; }
        public Nullable<int> LicTradNum { get; set; }
        public Nullable<int> DebPayAcct { get; set; }
        public Nullable<int> ShipToDef { get; set; }
        public Nullable<int> BillToDef { get; set; }
        public Nullable<int> ECVatGroup { get; set; }
        public string U_oldcardcode { get; set; }
        public string U_visitroute { get; set; }
        public string U_channel { get; set; }
        public Nullable<int> U_subchannel1 { get; set; }
        public Nullable<int> U_subchannel2 { get; set; }
        public Nullable<int> U_cust_promo_group { get; set; }
        public string U_supervisor { get; set; }
        public string U_vando { get; set; }
        public Nullable<int> U_salesorderpool { get; set; }
        public int U_distributor { get; set; }
        public string U_area { get; set; }
        public Nullable<int> U_dc { get; set; }
        public Nullable<int> U_disc_group { get; set; }
        public Nullable<int> U_noreserve { get; set; }
        public Nullable<int> U_department { get; set; }
    }
}
