//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CUSTOMERDT
    {
        public string Address { get; set; }
        public string CardCode { get; set; }
        public string AdresType { get; set; }
        public string Building { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string StreetNo { get; set; }
        public Nullable<int> LicTradNum { get; set; }
        public string GlblLocNum { get; set; }
        public string U_titlename { get; set; }
        public string U_name { get; set; }
        public string U_rounting { get; set; }
    }
}
