//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GetVanStock
    {
        public string ProductID { get; set; }
        public string PrdName { get; set; }
        public string ProductName { get; set; }
        public int VANCarQty { get; set; }
        public int VANPckQty { get; set; }
        public Nullable<decimal> RLCarQty { get; set; }
        public Nullable<decimal> RLPckQty { get; set; }
        public string DocNo { get; set; }
        public string DocStatus { get; set; }
        public string DocTypeCode { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string WHID { get; set; }
    }
}
