//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INVHD
    {
        public string DocNo { get; set; }
        public string Series { get; set; }
        public System.DateTime DocDate { get; set; }
        public string CardCode { get; set; }
        public string NumAtCard { get; set; }
        public decimal DiscPrcnt { get; set; }
        public decimal DiscSum { get; set; }
        public decimal VatSum { get; set; }
        public decimal TotalDue { get; set; }
        public string Comments { get; set; }
        public string ShipToCode { get; set; }
        public string PayToCode { get; set; }
        public string U_internal_remark { get; set; }
        public string U_obranch { get; set; }
        public string U_name { get; set; }
        public string U_routing { get; set; }
        public string U_doc_status { get; set; }
    }
}
