//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INVDT
    {
        public string DocNo { get; set; }
        public Nullable<short> LineNum { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string UomEntry { get; set; }
        public string UomCode { get; set; }
        public string VatGroup { get; set; }
        public string WhsCode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceBefDi { get; set; }
        public decimal PriceAfVAT { get; set; }
        public decimal VatSum { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public Nullable<int> OcrCode { get; set; }
        public Nullable<int> OcrCode2 { get; set; }
        public Nullable<int> OcrCode3 { get; set; }
        public string U_Free { get; set; }
    }
}
