//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StockMovement
    {
        public Nullable<System.DateTime> TrnDate { get; set; }
        public string RefDocNo { get; set; }
        public string TrnType { get; set; }
        public string WHID { get; set; }
        public string FromWHID { get; set; }
        public string ToWHID { get; set; }
        public int ProductGroupID { get; set; }
        public int ProductSubGroupID { get; set; }
        public short Seq { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> TrnQtyIn { get; set; }
        public Nullable<decimal> TrnQtyOut { get; set; }
        public Nullable<decimal> TrnQty { get; set; }
    }
}
