//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllCashUFormsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UBNDashboard
    {
        public string BillNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string WHID { get; set; }
        public string CustNo { get; set; }
        public Nullable<decimal> GAmt { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NAmt { get; set; }
        public Nullable<decimal> COGS { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string ProductRefCode { get; set; }
        public string ProductName { get; set; }
    }
}
